### ISSUE TITLE
Parameterless constructor

### ISSUE THREAD

**Issue by Simcon** [goblinfactory/comma-delimited#1]
Is there any reason why a parameter-less constructor wasn't included?

This seems bloated:

new CommaDelimLower(string.Empty)

Also without a parameterless constructor I can't use Automapper or Dapper.

**Comment by goblinfactory** [comment]
I wouldn't use this with Dapper. That breaks the robustness principle.
i.e. the purpose of comma-delimited is to give you the abiility to make your API easier to use and the code that uses it easier to write, (that's incoming data) and for outgoing data, you should use principle of least surprise, i.e. well known boring classes. 

Comma-delimited is designed specifically for APi that would get mapped to strongly typed domain objects, i.e. immediately mapped to boring string[] arrays, which then work with Dapper.

With that in mind, it definitely should work with Automapper to support that design goal.
I am testing now, .. adding paramterless constructor seems sensible.

**Comment by goblinfactory** [comment]
Updated package 1.2.0 has been published to Nuget with parameterless constructors for all classes. Please test with dapper and automapper. I'll close the issue in a few days. 
Feel free to close the issue earlier if you're comfortable with the changes. 
cheers, A

**Comment by Simcon** [comment]
Can confirm this works with Automapper - thanks!

Not sure what the issue is with Dapper but am happy to map to string[] for now. I'll investigate further. One red flag is I am mapping to PostgreSQL jsonb documents so there's a whole extra layer of misery and the problem may lie there. string[] FTW!

**Comment by goblinfactory** [comment]
most likely a reflection thing, they're quite simple objects so if we need to extend them to implement some interface so that they can be recognised I'll happy do that. Let me know if you find something specific I can do to help.

Take a look at this and see if this helps at all? talks about dapper and comma delimited types. I've not used dapper for a long time now since I started using memstate with azure.

https://medium.com/dapper-net/custom-type-handling-4b447b97c620

**Comment by goblinfactory** [comment]
Update (after very briefly scanning the  the dapper blogpost, and not actually trying any code) : just a thought? perhaps I need to create another package, `Goblinfactory.Delimited.Dapper` and create the custom dapper type handler?

**Comment by goblinfactory** [comment]
Happy to look at this for fun if you create a new issue, (I'll tag it as a feature request) ..e.g. please support Dapper ? 

mmm, just realised .. the tests for this will take a little time and I'm a bit focused on Konsole in my spare time, so I can't guarantee I'll get to this quickly, best to create the 6 or 7 line custom type handler yourself for now and if that link above works, I'll make a note in the readme of what anyone using dapper can do, ... though my recommendation is still... don't pass down custom objects to third party libraries if you can easily avoid it.

**Comment by Simcon** [comment]
> Update (after very briefly scanning the the dapper blogpost, and not actually trying any code) : just a thought? perhaps I need to create another package, `Goblinfactory.Delimited.Dapper` and create the custom dapper type handler?

I think this is going beyond. I'm happy to have Delim working across UI and services layers and switch to primitives for data. Otherwise where do you draw the line?
